spring:
  datasource:
    url: jdbc:mysql://192.168.60.231:3306/fayuan_test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 123456

  jooq:
    sql-dialect: MYSQL